// Palette import/export formats, ported from AG Color Palette. Text formats
// return a string; binary formats (ASE/ACO) return a Uint8Array. All hex
// inputs/outputs are 6-digit, no '#'.
import { hexToRgb, hexToHsl } from './color';

export type ExportFormat = 'ase' | 'aco' | 'css' | 'tailwind' | 'json';

export const FORMAT_LABELS: Record<ExportFormat, string> = {
  ase: 'ASE (Adobe Swatch)',
  aco: 'ACO (Photoshop)',
  css: 'CSS Variables',
  tailwind: 'Tailwind Config',
  json: 'JSON (named)',
};

const bare = (hex: string) => hex.replace(/^#/, '').toUpperCase();
const slugify = (s: string) => s.replace(/[^a-zA-Z0-9_-]/g, '-').toLowerCase() || 'palette';

// --- Byte buffer helpers for the binary formats ---
class ByteWriter {
  private bytes: number[] = [];
  u8(n: number) { this.bytes.push(n & 0xff); }
  u16(n: number) { this.u8(n >> 8); this.u8(n); }
  u32(n: number) { this.u8(n >>> 24); this.u8(n >>> 16); this.u8(n >>> 8); this.u8(n); }
  ascii(s: string) { for (let i = 0; i < s.length; i++) this.u8(s.charCodeAt(i)); }
  utf16be(s: string) { for (let i = 0; i < s.length; i++) this.u16(s.charCodeAt(i)); }
  f32(v: number) {
    const dv = new DataView(new ArrayBuffer(4));
    dv.setFloat32(0, v, false); // big-endian
    for (let i = 0; i < 4; i++) this.u8(dv.getUint8(i));
  }
  toUint8Array() { return new Uint8Array(this.bytes); }
}

const writeASE = (hexes: string[]): Uint8Array => {
  const w = new ByteWriter();
  w.ascii('ASEF');
  w.u16(1); w.u16(0);          // version 1.0
  w.u32(hexes.length);         // block count
  for (const h of hexes) {
    const name = '#' + bare(h);
    const nameLen = name.length + 1;            // includes null terminator
    const blockLen = 2 + nameLen * 2 + 4 + 12 + 2;
    w.u16(0x0001);
    w.u32(blockLen);
    w.u16(nameLen);
    w.utf16be(name);
    w.u16(0);                                    // null terminator
    w.ascii('RGB ');
    const [r, g, b] = hexToRgb(h) ? [hexToRgb(h)!.r / 255, hexToRgb(h)!.g / 255, hexToRgb(h)!.b / 255] : [0, 0, 0];
    w.f32(r); w.f32(g); w.f32(b);
    w.u16(0);                                    // color type: global
  }
  return w.toUint8Array();
};

const writeACO = (hexes: string[]): Uint8Array => {
  const w = new ByteWriter();
  const rgb16 = (h: string) => {
    const c = hexToRgb(h) ?? { r: 0, g: 0, b: 0 };
    return [Math.round((c.r / 255) * 65535), Math.round((c.g / 255) * 65535), Math.round((c.b / 255) * 65535)];
  };
  // Version 1 section
  w.u16(1); w.u16(hexes.length);
  for (const h of hexes) { const [r, g, b] = rgb16(h); w.u16(0); w.u16(r); w.u16(g); w.u16(b); w.u16(0); }
  // Version 2 section (with names)
  w.u16(2); w.u16(hexes.length);
  for (const h of hexes) {
    const [r, g, b] = rgb16(h);
    w.u16(0); w.u16(r); w.u16(g); w.u16(b); w.u16(0);
    const name = '#' + bare(h);
    w.u32(name.length + 1);
    w.utf16be(name);
    w.u16(0);
  }
  return w.toUint8Array();
};

const writeCSS = (hexes: string[], name: string): string => {
  const slug = slugify(name);
  const lines = [`/* ${name} - generated by Motion Color */`, ':root {'];
  hexes.forEach((h, i) => lines.push(`    --${slug}-${i + 1}: #${bare(h)};`));
  lines.push('}');
  return lines.join('\n') + '\n';
};

const writeTailwind = (hexes: string[], name: string): string => {
  const slug = slugify(name);
  const lines = [
    `// ${name} - generated by Motion Color`,
    '// Drop into tailwind.config.js → theme.extend.colors',
    'module.exports = {',
    `    ${JSON.stringify(slug)}: {`,
  ];
  hexes.forEach((h, i) => {
    const key = String((i + 1) * 100);
    const trail = i === hexes.length - 1 ? '' : ',';
    lines.push(`        "${key}": "#${bare(h)}"${trail}`);
  });
  lines.push('    }', '};');
  return lines.join('\n') + '\n';
};

const writeNamedJSON = (hexes: string[], name: string): string => {
  const colors = hexes.map((h, i) => {
    const rgb = hexToRgb(h) ?? { r: 0, g: 0, b: 0 };
    const hsl = hexToHsl(h) ?? { h: 0, s: 0, l: 0 };
    return {
      name: 'color' + (i + 1),
      hex: '#' + bare(h),
      rgb: [rgb.r, rgb.g, rgb.b],
      hsl: [Math.round(hsl.h), Math.round(hsl.s), Math.round(hsl.l)],
    };
  });
  return JSON.stringify({ name, colors }, null, 4);
};

export interface BuiltExport { ext: ExportFormat; binary: boolean; data: string | Uint8Array }

export const buildExport = (format: ExportFormat, hexes: string[], paletteName: string): BuiltExport => {
  switch (format) {
    case 'ase': return { ext: 'ase', binary: true, data: writeASE(hexes) };
    case 'aco': return { ext: 'aco', binary: true, data: writeACO(hexes) };
    case 'css': return { ext: 'css', binary: false, data: writeCSS(hexes, paletteName) };
    case 'tailwind': return { ext: 'tailwind', binary: false, data: writeTailwind(hexes, paletteName) };
    case 'json': return { ext: 'json', binary: false, data: writeNamedJSON(hexes, paletteName) };
  }
};

// --- ASE import ---
const f32be = (dv: DataView, o: number) => dv.getFloat32(o, false);

export const parseAseBytes = (buf: Uint8Array): string[] => {
  const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  const toHex = (v: number) => Math.max(0, Math.min(255, Math.round(v * 255))).toString(16).padStart(2, '0').toUpperCase();
  const rgbHex = (r: number, g: number, b: number) => toHex(r) + toHex(g) + toHex(b);

  // Signature "ASEF"
  if (String.fromCharCode(buf[0], buf[1], buf[2], buf[3]) !== 'ASEF') return [];
  let o = 8;                                   // skip signature + version
  const blockCount = dv.getUint32(o, false); o += 4;
  const out: string[] = [];

  for (let i = 0; i < blockCount && o + 6 <= buf.length; i++) {
    const blockType = dv.getUint16(o, false); o += 2;
    const blockLen = dv.getUint32(o, false); o += 4;
    if (blockType === 0x0001) {
      const nameLen = dv.getUint16(o, false); o += 2;
      o += nameLen * 2;                        // skip UTF-16 name (incl. null)
      const model = String.fromCharCode(buf[o], buf[o + 1], buf[o + 2], buf[o + 3]); o += 4;
      if (model === 'RGB ') {
        out.push(rgbHex(f32be(dv, o), f32be(dv, o + 4), f32be(dv, o + 8))); o += 12;
      } else if (model === 'CMYK') {
        const c = f32be(dv, o), m = f32be(dv, o + 4), y = f32be(dv, o + 8), k = f32be(dv, o + 12); o += 16;
        out.push(rgbHex(1 - Math.min(1, c * (1 - k) + k), 1 - Math.min(1, m * (1 - k) + k), 1 - Math.min(1, y * (1 - k) + k)));
      } else if (model === 'Gray') {
        const v = f32be(dv, o); o += 4; out.push(rgbHex(v, v, v));
      } else if (model === 'LAB ') {
        o += 12;                               // LAB import is rare; skip the triple
      }
      o += 2;                                  // color-type marker
    } else {
      o += blockLen;                           // group start/end — skip
    }
  }
  return out;
};
